# Generated by Django 2.2.3 on 2020-04-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('firm_name', models.CharField(max_length=255, null=True)),
                ('address', models.TextField()),
                ('gstin', models.CharField(max_length=15, null=True)),
                ('primary_num', models.IntegerField(null=True)),
                ('secondary_num', models.IntegerField(null=True)),
                ('category', models.CharField(choices=[('G', 'General'), ('A', 'Category A'), ('B', 'Category B')], max_length=20)),
            ],
        ),
    ]
