# Generated by Django 3.0.5 on 2020-05-11 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('firm_name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('gstin', models.CharField(blank=True, max_length=15, null=True)),
                ('primary_num', models.BigIntegerField(blank=True, null=True)),
                ('secondary_num', models.BigIntegerField(blank=True, null=True)),
                ('category', models.CharField(default='Category General', max_length=16)),
            ],
        ),
    ]
