# Generated by Django 2.2.3 on 2020-04-24 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='category',
            field=models.CharField(choices=[('General', 'G'), ('Category A', 'A'), ('Category B', 'B')], max_length=10),
        ),
    ]
